--DROP TABLE STG_LICENCIAS_MEDICAS;
-- Create table
CREATE TABLE STG_LICENCIAS_MEDICAS
   (PER_RUT 		 NUMBER, 
	DEP_FECINI 		 TIMESTAMP (9), 
	FML_FORMUL 	 	 VARCHAR2(255) COLLATE "USING_NLS_COMP",
	LIC_NUMLIC 		 NUMBER, 
	DEP_DIALIC 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	TCT_TIPCTA 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	BAN_CODBAN 		 NUMBER, 
	DEP_CTABAN 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_CORREOE 	 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_AREAFONO 	 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_FONO 		 NUMBER, 
	DEP_AREAFONO_COM VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_FONO_COM 	 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_CELULAR 	 NUMBER, 
	DEP_FECTERVIGEN  VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_LUGAR 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_ESTADO 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_FECGRA 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_USUGRA 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_FECACT 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_USUACT 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	DEP_CANAL 		 VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	NEW_STATUS 		 VARCHAR(255) COLLATE "USING_NLS_COMP"
)
tablespace DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  )
compress;
